
const DATA_URL='data/report.json';
const LS_MODE='atletix_github_mode_v1';
const LS_PERIOD='atletix_github_period_v1';
const LS_REVIEW='atletix_review_choices_v1';
let report=null, mode=localStorage.getItem(LS_MODE)||'half', rows=[];
function money(n){n=Number(n||0);return '$'+n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});}
function num(n){return Number(n||0).toLocaleString('en-US');}
function esc(s){return String(s==null?'':s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function dateFmt(s){if(!s)return'';const d=new Date(s);return d.toLocaleDateString('en-US',{day:'numeric',month:'short',year:'numeric'});}
function keyOf(r){return r.manual_id||String(r.order_id||'')+'_'+String(r.product||'')+'_'+String(r.quantity||'');}
function yearOf(r){const d=new Date(r.order_date);return d.getFullYear();}
function monthOf(r){const d=new Date(r.order_date);return d.getMonth()+1;}
function qOf(m){return Math.floor((m-1)/3)+1;}
function halfOf(m){return m<=6?'H1':'H2';}
function periodKeyForRow(r){const y=yearOf(r),m=monthOf(r);return {month:`M:${y}:${m}`,quarter:`Q:${y}:${qOf(m)}`,half:`H:${y}:${halfOf(m)}`};}
function toggleTheme(){const cur=document.documentElement.dataset.theme||'light';const next=cur==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('theme',next);document.getElementById('themeBtn').textContent=next==='dark'?'Light':'Dark';}
(function(){const t=localStorage.getItem('theme')||'light';document.documentElement.dataset.theme=t;})()
async function loadData(cacheBust=false){try{document.getElementById('main').className='loading';document.getElementById('main').textContent='Loading latest GitHub data...';const res=await fetch(DATA_URL+(cacheBust?'?t='+Date.now():''),{cache:cacheBust?'reload':'default'});if(!res.ok)throw new Error('Could not load data/report.json');report=await res.json();rows=(report.rows||[]).concat(report.manual_defaults||[]);buildPeriodSelect();loadView();}catch(e){document.getElementById('main').className='';document.getElementById('main').innerHTML='<div class="err">'+esc(e.message)+'</div>';}}
function reloadData(){loadData(true);}
function setMode(m){mode=m;localStorage.setItem(LS_MODE,m);buildPeriodSelect();loadView();}
function periodMode(){return (mode==='rotation'||mode==='turnover')?'half':mode;}
function buildPeriodSelect(){['Month','Quarter','Half','Rotation','Turnover'].forEach(x=>{const el=document.getElementById('tab'+x);if(el)el.classList.toggle('active',mode===x.toLowerCase());});const sel=document.getElementById('periodSelect');const saved=localStorage.getItem(LS_PERIOD)||'';const pm=periodMode();let opts=[];const seen=new Set();const now=new Date();
 rows.forEach(r=>{if(!r.order_date)return;const y=yearOf(r),m=monthOf(r);if(!y||!m)return;if(pm==='month'){const k=`M:${y}:${m}`;if(!seen.has(k)){seen.add(k);opts.push({k,label:new Date(y,m-1,1).toLocaleString('en-US',{month:'long',year:'numeric'}),sort:y*100+m});}} if(pm==='quarter'){const q=qOf(m),k=`Q:${y}:${q}`;if(!seen.has(k)){seen.add(k);opts.push({k,label:`Q${q} ${y}`,sort:y*10+q});}} if(pm==='half'){const h=halfOf(m),k=`H:${y}:${h}`;if(!seen.has(k)){seen.add(k);opts.push({k,label:`${h} ${y} (${h==='H1'?'Jan - Jun':'Jul - Dec'})`,sort:y*10+(h==='H1'?1:2)});}}});
 if(pm==='half'){const cy=now.getFullYear();['H1','H2'].forEach((h,i)=>{const k=`H:${cy}:${h}`;if(!seen.has(k)){seen.add(k);opts.push({k,label:`${h} ${cy} (${h==='H1'?'Jan - Jun':'Jul - Dec'})`,sort:cy*10+i+1});}})}
 opts.sort((a,b)=>b.sort-a.sort);sel.innerHTML=opts.map(o=>`<option value="${o.k}">${o.label}</option>`).join(''); if(opts.find(o=>o.k===saved)) sel.value=saved; else if(pm==='half'){const h1=`H:${now.getFullYear()}:H1`;sel.value=opts.find(o=>o.k===h1)?.k||opts[0]?.k||'';} else sel.value=opts[0]?.k||'';}
function selectedRows(){const k=document.getElementById('periodSelect').value;localStorage.setItem(LS_PERIOD,k);const pm=periodMode();return rows.filter(r=>{const p=periodKeyForRow(r);return p[pm]===k;});}
function periodLabel(){const sel=document.getElementById('periodSelect');return sel.options[sel.selectedIndex]?.textContent||'-';}
function loadView(){if(!report)return;document.getElementById('periodLabel').textContent=periodLabel().split(' (')[0];if(mode==='half')renderReview(); else if(mode==='rotation')renderInventoryRotation(); else if(mode==='turnover')renderInventoryTurnover(); else renderStandard();}
function readReview(){try{return JSON.parse(localStorage.getItem(LS_REVIEW)||'{}')}catch(e){return {}}}
function writeReview(v){localStorage.setItem(LS_REVIEW,JSON.stringify(v));}
function stateFor(r){const all=readReview();const k=keyOf(r);if(!all[k]){all[k]={included:r.type!=='Atletix Request'?true:true,countType:r.type==='Atletix Request'?'request':'regular',shipping:Number(r.manual_shipping||0),note:r.note||'',edits:{}};writeReview(all);}return all[k];}
function setRow(k,patch){const all=readReview();all[k]=Object.assign({},all[k]||{},patch);writeReview(all);renderReview();}
function sectionType(r,st){if(!st.included)return 'excluded'; if(st.countType==='request'||r.type==='Atletix Request')return 'request'; if(r.type==='Marketing / Seeded')return 'marketing'; if(r.type==='Credit / Return')return 'return'; return 'regular';}
function calcReview(){const list=selectedRows();const states=list.map(r=>[r,stateFor(r)]);let totalOrders=new Set(), excludedOrders=[], totalUnits=0, excludedUnits=0,totalCogs=0,cogsExcluded=0,shipping=0;states.forEach(([r,st])=>{totalOrders.add(r.order_id);const qty=Number(st.edits?.quantity??r.quantity??0);const unit=Number(st.edits?.unit_cogs??r.unit_cogs??0);const cogs=Math.round(qty*unit*100)/100;totalUnits+=Math.max(qty,0);totalCogs+=cogs;const isRemoved=!st.included||st.countType==='request'||r.type==='Atletix Request';if(isRemoved){excludedUnits+=Math.max(qty,0);cogsExcluded+=cogs;if(!st.included)excludedOrders.push(r.order_id);}if(st.included)shipping+=Number(st.shipping||0);});totalCogs=Math.round(totalCogs*100)/100;cogsExcluded=Math.round(cogsExcluded*100)/100;shipping=Math.round(shipping*100)/100;const netCogs=Math.max(0,Math.round((totalCogs-cogsExcluded)*100)/100);return{list,states,totalOrders:totalOrders.size,totalExcluded:new Set(excludedOrders).size,totalUnits,excludedUnits,totalCogs,originalProductCogs:totalCogs,netCogs,finalCogs:netCogs,cogsExcluded,shipping,invoice:Math.round((netCogs+shipping)*100)/100,excludedOrders:[...new Set(excludedOrders)]};}
function periodBounds(){const k=document.getElementById('periodSelect').value||'';const parts=k.split(':');const y=Number(parts[1]);if(parts[0]==='M'){const m=Number(parts[2]);return{start:new Date(Date.UTC(y,m-1,1)),end:new Date(Date.UTC(y,m,1))};}if(parts[0]==='Q'){const q=Number(parts[2]);const sm=(q-1)*3;return{start:new Date(Date.UTC(y,sm,1)),end:new Date(Date.UTC(y,sm+3,1))};}if(parts[0]==='H'){const h=parts[2];return{start:new Date(Date.UTC(y,h==='H1'?0:6,1)),end:new Date(Date.UTC(y,h==='H1'?6:12,1))};}return{start:new Date(0),end:new Date()};}
function inventoryMetrics(){const cfg=report.config||{};const unit=Number(cfg.unit_cogs||89);const initial=Number(cfg.initial_stock||100);const b=periodBounds();function rowQty(r){return Math.max(Number(r.quantity||0),0)}const beforeUnits=rows.filter(r=>r.order_date&&new Date(r.order_date)<b.start).reduce((s,r)=>s+rowQty(r),0);const periodRows=selectedRows();const unitsSold=periodRows.reduce((s,r)=>s+rowQty(r),0);const opening=Math.max(0,initial-beforeUnits);const ending=Math.max(0,opening-unitsSold);const avgUnits=(opening+ending)/2;const totalCogs=round2(unitsSold*unit);const openingValue=round2(opening*unit);const endingValue=round2(ending*unit);const avgValue=round2(avgUnits*unit);const rotation=avgUnits>0?round2(unitsSold/avgUnits):0;const turnover=avgValue>0?round2(totalCogs/avgValue):0;return{unit,initial,opening,ending,avgUnits,unitsSold,totalCogs,openingValue,endingValue,avgValue,rotation,turnover};}
function metricKpis(m,kind){return `<div class="grid review-grid">${card('Opening Inventory',num(m.opening),'Units available at the beginning of the selected period.','good')}${card('Ending Inventory',num(m.ending),'Opening inventory minus units sold / moved in the period.')}${card('Units Sold',num(m.unitsSold),'Total units moved in the selected period.','good')}${card(kind==='turnover'?'Inventory Turnover':'Inventory Rotation',num(kind==='turnover'?m.turnover:m.rotation)+'x',kind==='turnover'?'COGS / COX divided by average inventory value.':'Units sold divided by average inventory units.','final hero')}${card('Average Inventory Units',num(round2(m.avgUnits)),'(Opening units + Ending units) / 2')}${card('Unit COGS / COX',money(m.unit),'Configured product cost used for inventory value.')}${card('Total COGS / COX',money(m.totalCogs),'Units sold × Unit COGS / COX.','final')}${card('Average Inventory Value',money(m.avgValue),'Average inventory units × Unit COGS / COX.','final')}</div>`;}
function renderInventoryRotation(){const m=inventoryMetrics();let html=`<div class="notice"><b>${esc(periodLabel().split(' (')[0])}</b> · Inventory Rotation measures unit movement. This replaces the previous unit-based turnover view.</div><div class="slbl">Inventory Rotation KPIs</div>${metricKpis(m,'rotation')}<div class="formula-card"><b>Formula used:</b> Inventory Rotation = Units Sold ÷ Average Inventory Units.<br><b>Current calculation:</b> ${num(m.unitsSold)} ÷ ${num(round2(m.avgUnits))} = ${num(m.rotation)}x.<div class="field-list"><div class="field-chip"><b>Opening Inventory</b> Units available at the start of the period.</div><div class="field-chip"><b>Ending Inventory</b> Units remaining after period movement.</div><div class="field-chip"><b>Average Inventory Units</b> (Opening Inventory + Ending Inventory) / 2.</div><div class="field-chip"><b>Units Sold</b> Total Atletix units moved during the selected period.</div></div></div>`;document.getElementById('main').className='';document.getElementById('main').innerHTML=html;}
function renderInventoryTurnover(){const m=inventoryMetrics();let html=`<div class="notice"><b>${esc(periodLabel().split(' (')[0])}</b> · Inventory Turnover uses the standard value-based formula. It should not be confused with unit rotation.</div><div class="slbl">Inventory Turnover KPIs</div>${metricKpis(m,'turnover')}<div class="formula-card"><b>Formula used:</b> Inventory Turnover = COGS / COX ÷ Average Inventory Value.<br><b>Current calculation:</b> ${money(m.totalCogs)} ÷ ${money(m.avgValue)} = ${num(m.turnover)}x.<div class="field-list"><div class="field-chip"><b>COGS / COX</b> Units sold × Unit COGS / COX for the selected period.</div><div class="field-chip"><b>Opening Inventory Value</b> Opening units × Unit COGS / COX: ${money(m.openingValue)}.</div><div class="field-chip"><b>Ending Inventory Value</b> Ending units × Unit COGS / COX: ${money(m.endingValue)}.</div><div class="field-chip"><b>Average Inventory Value</b> (Opening value + Ending value) / 2.</div></div></div>`;document.getElementById('main').className='';document.getElementById('main').innerHTML=html;}
function card(label,val,desc,cls=''){return `<div class="card ${cls}"><div class="lbl">${esc(label)}</div><div class="val">${esc(val)}</div><div class="desc">${esc(desc)}</div></div>`}
function renderReview(){const c=calcReview();const label=periodLabel().split(' (')[0];let html=`<div class="notice"><b>${esc(label)}</b> · Review by category. Add manual Atletix requests for inventory reconciliation. Use Atletix Request when product COGS / COX should be removed and only shipping should apply.</div><div class="tools"><button class="btn" onclick="clearReview()">Clear Review Choices</button><button class="btn" onclick="downloadCsv()">Download CSV</button></div>`;
const loaded=(c.states.filter(([r,st])=>st.countType==='request'&&st.included&&Number(st.shipping||0)>0).map(([r,st])=>`<span class="mini-pill">${esc(r.customer)} · ${esc(r.order_id)} · ${money(st.shipping)}</span>`).join('')); if(loaded) html+=`<div class="loaded-shipping"><b>Atletix-paid shipping details loaded:</b><br>${loaded}</div>`;
html+=`<div class="slbl">${esc(label)} Totals</div><div class="grid review-grid">${card('Total Orders for Period',num(c.totalOrders),'All Atletix orders found in the selected period.','good')}${card('Total Units Sold',num(c.totalUnits),'Total units sold in the selected period.','good')}${card('Inventory Turnover',num(inventoryMetrics().turnover)+'x','COGS / COX divided by average inventory value.','final')}${card('Excluded / Atletix Request Units',num(c.excludedUnits),'Units removed from product COGS / COX: unchecked rows plus Atletix Request rows.','warn')}${card('Total COGS / COX',money(c.totalCogs),'Gross product COGS before exclusions.','final')}${card('COGS Excluded',money(c.cogsExcluded),'Product COGS / COX excluded for removed or Atletix Request rows.','warn')}${card('Total Shipping Charges',money(c.shipping),'Manual shipping entered for this review.','final')}${card('Final Invoice Due',money(c.invoice),'Total COGS / COX minus COGS Excluded plus Total Shipping Charges.','final hero')}${card('Total Orders Excluded',num(c.totalExcluded),'Orders unchecked and removed from this review.','warn')}</div><div class="summary-note"><span><b>Excluded Orders:</b> ${esc(c.excludedOrders.length?c.excludedOrders.join(', '):'None')}</span><span><b>Invoice total:</b> ${money(c.invoice)}</span></div>`;
html+=manualForm();
html+=section('Regular / Commercial Orders',c.states.filter(([r,st])=>sectionType(r,st)==='regular'));
html+=section('Marketing / Seeded Orders',c.states.filter(([r,st])=>sectionType(r,st)==='marketing'));
html+=section('Atletix Requests / Shipping Only',c.states.filter(([r,st])=>sectionType(r,st)==='request'));
html+=section('Excluded Orders',c.states.filter(([r,st])=>sectionType(r,st)==='excluded'));
html+=`<div class="footer">Generated by GitHub Actions: ${esc(report.generated_at||'')} · Refresh reloads the latest generated JSON. Shopify update runs by GitHub Actions schedule/manual workflow.</div>`;
document.getElementById('main').className='';document.getElementById('main').innerHTML=html;}
function pill(r){let cls='reg',label='Commercial'; if(r.type==='Marketing / Seeded'){cls='mkt';label='Marketing / Seeded'} if(r.type==='Atletix Request'){cls='req';label='Atletix Request'} if(r.type==='Credit / Return'){cls='ret';label='Credit / Return'} return `<span class="pill ${cls}">${label}</span><div class="source">Source: ${esc(r.category_source||r.reason||'')}</div>`}
function section(title,arr){return `<div class="slbl">${esc(title)}<span class="badge-count">${arr.length} rows</span></div>${arr.length?table(arr):'<div class="empty">No rows in this section.</div>'}`;}
function table(arr){return `<div class="table-wrap"><table class="tbl"><thead><tr><th>Order #</th><th>Date</th><th>Customer</th><th>Product</th><th>Category</th><th class="r">Qty</th><th class="r">Net</th><th class="r">Unit COGS</th><th class="r">Original COGS</th><th>Include in Totals</th><th>How to Count</th><th>Manual Shipping</th><th>Note</th></tr></thead><tbody>${arr.map(([r,st])=>rowHtml(r,st)).join('')}</tbody></table></div>`}
function rowHtml(r,st){const k=keyOf(r),qty=Number(st.edits?.quantity??r.quantity??0),unit=Number(st.edits?.unit_cogs??r.unit_cogs??0);return `<tr><td data-label="Order #">${esc(r.order_id)}</td><td data-label="Date">${dateFmt(r.order_date)}</td><td data-label="Customer">${esc(st.edits?.customer??r.customer)}<div class="email">${esc(r.customer_email||'')}</div></td><td data-label="Product">${esc(st.edits?.product??r.product)}<div class="mini">${esc((st.edits?.variant ?? r.variant) || '')}</div></td><td data-label="Category">${pill(r)}</td><td data-label="Qty" class="r">${num(qty)}</td><td data-label="Net" class="r money">${money(r.net)}</td><td data-label="Unit COGS" class="r money">${money(unit)}</td><td data-label="Original COGS" class="r money">${money(qty*unit)}</td><td data-label="Include"><label><input type="checkbox" ${st.included?'checked':''} onchange="setRow('${k}',{included:this.checked})"> Add to totals</label><div class="mini">Uncheck to exclude from review totals.</div></td><td data-label="How to Count" class="row-actions"><button class="btn choice ${st.countType!=='request'?'active':''}" onclick="setRow('${k}',{countType:'regular',included:true})">Regular Order</button><button class="btn choice ${st.countType==='request'?'active':''}" onclick="setRow('${k}',{countType:'request',included:true})">Atletix Request</button><div class="mini">Atletix Request = product COGS / COX excluded, shipping only.</div></td><td data-label="Shipping"><input class="ship-input" value="${esc(st.shipping||0)}" onchange="setRow('${k}',{shipping:Number(this.value.replace(',','.'))||0})"></td><td data-label="Note"><input class="note-input" value="${esc(st.note||'')}" onchange="setRow('${k}',{note:this.value})"></td></tr>`}
function manualForm(){return `<div class="manual-box"><div class="slbl" style="margin-top:0">Add / Update Manual Atletix Request</div><div class="manual-grid"><input id="mCustomer" placeholder="Customer" value="Mirko Midili"><input id="mId" placeholder="Manual ID" value="MANUAL-MIRKO-H1-2026"><input id="mQty" placeholder="Qty" value="4"><input id="mUnit" placeholder="Unit COGS / COX" value="89"><input id="mShipping" placeholder="Shipping" value="17.33"><input id="mDate" placeholder="Date YYYY-MM-DD" value="2026-06-30"><textarea id="mNote" placeholder="Address / phone / notes">MIRKO MIDILI | 4412 Las Colinas Ln | Norman, OK 73072 | Phone: +1 580 559 6577</textarea><button class="btn btn-primary" onclick="addManual()">Add / Update Manual Row</button></div></div>`;}
function addManual(){const id=document.getElementById('mId').value.trim()||'MANUAL-'+Date.now();const q=Number(document.getElementById('mQty').value)||0,u=Number(document.getElementById('mUnit').value)||0;const row={manual_id:id,order_id:id,order_date:(document.getElementById('mDate').value||new Date().toISOString().slice(0,10))+'T12:00:00Z',customer:document.getElementById('mCustomer').value||'Manual Atletix Request',customer_email:'',product:'Atletix Horse',variant:'60 Doses',sku:report.config?.sku||'ATLETIX60',quantity:q,gross:0,discount:0,net:0,unit_cogs:u,cogs:q*u,type:'Atletix Request',reason:'Manual Atletix shipment not found in Shopify',category_source:'Manual review entry',manual_shipping:Number(document.getElementById('mShipping').value)||0,note:document.getElementById('mNote').value,is_manual:true};rows=rows.filter(r=>keyOf(r)!==id).concat([row]);const all=readReview();all[id]={included:true,countType:'request',shipping:row.manual_shipping,note:row.note,edits:{customer:row.customer,product:row.product,variant:row.variant,quantity:q,unit_cogs:u}};writeReview(all);buildPeriodSelect();document.getElementById('periodSelect').value=periodKeyForRow(row).half;renderReview();}
function clearReview(){if(confirm('Clear local review choices?')){localStorage.removeItem(LS_REVIEW);renderReview();}}
function renderStandard(){const list=selectedRows();const totalUnits=list.reduce((s,r)=>s+Number(r.quantity||0),0), cogs=list.reduce((s,r)=>s+Number(r.cogs||0),0), net=list.reduce((s,r)=>s+Number(r.net||0),0), gross=list.reduce((s,r)=>s+Number(r.gross||0),0), disc=list.reduce((s,r)=>s+Number(r.discount||0),0);let html=`<div class="slbl">Core KPIs</div><div class="grid">${card('Gross Sales',money(gross),'All Atletix line gross sales.')}${card('Units in Range',num(totalUnits),'Commercial + marketing + credits.')}${card('Net Sales',money(net),'Gross sales minus discounts.')}${card('Number of Orders',num(new Set(list.map(r=>r.order_id)).size),'Unique Atletix orders.')}${card('Discount',money(disc),'Total line discounts.')}${card('COGS',money(cogs),'Qty x unit cost.')}</div>`;html+=section('Commercial Sales',list.filter(r=>r.type==='Commercial').map(r=>[r,stateFor(r)]));html+=section('Marketing Activities / Seeded Units',list.filter(r=>r.type==='Marketing / Seeded').map(r=>[r,stateFor(r)]));html+=section('Atletix Requests / Shipping Only',list.filter(r=>r.type==='Atletix Request').map(r=>[r,stateFor(r)]));document.getElementById('main').className='';document.getElementById('main').innerHTML=html;document.getElementById('periodLabel').textContent=periodLabel();}
function downloadCsv(){const c=calcReview();const lines=[];lines.push(['Metric','Value']);[['Period',periodLabel()],['Generated',report.generated_at],['Total Orders for Period',c.totalOrders],['Total Orders Excluded',c.totalExcluded],['Total Units Sold',c.totalUnits],['Excluded / Atletix Request Units',c.excludedUnits],['Total COGS / COX',c.totalCogs],['COGS Excluded',c.cogsExcluded],['Net COGS / COX',c.netCogs],['Total Shipping Charges',c.shipping],['Final Invoice Due',c.invoice],['Excluded Orders',c.excludedOrders.join(' | ')]].forEach(x=>lines.push(x));lines.push([]);lines.push(['Order #','Date','Customer','Email','Product','Category','Category Source','Qty','Net','Unit COGS','Original COGS','Included','Count Type','Manual Shipping','Note']);c.states.forEach(([r,st])=>lines.push([r.order_id,dateFmt(r.order_date),st.edits?.customer??r.customer,r.customer_email,st.edits?.product??r.product,r.type,r.category_source||r.reason,st.edits?.quantity??r.quantity,r.net,st.edits?.unit_cogs??r.unit_cogs,(st.edits?.quantity??r.quantity)*(st.edits?.unit_cogs??r.unit_cogs),st.included,st.countType,st.shipping,st.note]));const csv=lines.map(a=>a.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='atletix_'+periodLabel().replace(/[^a-z0-9]+/gi,'_').toLowerCase()+'.csv';a.click();URL.revokeObjectURL(url);}
loadData();
